# Project information
site_name: SimProp Sirente
site_url: https://simprop.github.io/
site_author: SimProp DevTeam
site_description: Monte Carlo simulation code of ultra-high energy cosmic ray propagation.

# Repository
repo_name: SimProp/simprop
repo_url: https://simprop.github.io/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 SimProp DevTeam
    
# Configuration
theme:
  name: material
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  icon:
    admonition:
      note: fontawesome/solid/sticky-note
      abstract: fontawesome/solid/book
      info: fontawesome/solid/info-circle
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/question-circle
      warning: fontawesome/solid/exclamation-triangle
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# versioning
# extra:
#  analytics:
#    provider: google
#    property: !ENV GOOGLE_ANALYTICS_KEY
#  version:
#    provider: mike
    
# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
    - Changelog: changelog.md
    - License: license.md
    - How to cite SimProp: howtocite.md
  - Physics reference manual:
    - reference/index.md
    - Cosmology: reference/cosmology.md
    - Photon Fields: reference/phfields.md
  - Additional resources:
    - additional/index.md
    - Data credits: additional/data.md
    - DevTeam: additional/team.md

