# Project information
site_name: SimProp Sirente
site_url: https://simprop.github.io/
site_author: SimProp DevTeam
site_description: Monte Carlo simulation code of ultra-high energy cosmic ray propagation.

# Repository
repo_name: SimProp/simprop
repo_url: https://simprop.github.io/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 SimProp DevTeam

# versioning
extra:
  version:
    provider: mike

# theme
theme:
  name: material
  language: en
  hljs_languages: c++
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
    - Changelog: changelog.md
    - License: license.md
    - How to cite SimProp: howtocite.md
  - Physics reference manual:
    - reference/index.md
    - Cosmology: reference/cosmology.md
    - Photon Fields: reference/phfields.md
  - Additional resources:
    - additional/index.md
    - Data credits additional/data.md
    - DevTeam additional/team.md

